---
- name: Instalar e configurar o NGINX
  hosts: web
  vars:
    ansible_python_interpreter: /usr/bin/python3.9
  become: yes
  tasks:
    - name: Pausar por 10 segundos para garantir que a instância seja criada
      pause:
        seconds: 10
    
    - name: Atualizar o sistema
      dnf:
        name: '*'
        state: latest

    - name: Instalar o NGINX
      dnf:
        name: nginx
        state: present

    - name: Garantir que o serviço NGINX esteja rodando
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copiar arquivo index.html para o servidor
      copy:
        src: site/index.html
        dest: /usr/share/nginx/html/index.html
        owner: nginx
        group: nginx
        mode: '0644'

    - name: Copiar arquivo script.js para o servidor
      copy:
        src: site/script.js
        dest: /usr/share/nginx/html/script.js
        owner: nginx
        group: nginx
        mode: '0644'

    - name: Copiar arquivo style.css para o servidor
      copy:
        src: site/style.css
        dest: /usr/share/nginx/html/style.css
        owner: nginx
        group: nginx
        mode: '0644'
    
    - name: Copiar o arquivo de configuração do NGINX com HTTPS habilitado
      copy:
        src: ../certificado/nginx.conf
        dest: /home/ec2-user/nginx.conf
        owner: nginx
        group: nginx
        mode: '0644'

    - name: Mover o arquivo de configuração para /etc/nginx
      command: mv /home/ec2-user/nginx.conf /etc/nginx/nginx.conf
      become: true

    - name: Copiar o script que gera o certificado HTTPS
      copy:
        src: ../certificado/setup_nginx_https.sh
        dest: /home/ec2-user/setup_nginx_https.sh
        owner: nginx
        group: nginx
        mode: '0755'

    - name: Executar o script de setup do HTTPS
      command: /home/ec2-user/setup_nginx_https.sh
      become: true

  handlers:
    - name: Reiniciar NGINX
      service:
        name: nginx
        state: restarted
